### ISSUE TITLE
Update project README to replace Google Code link with nupkg download link?

### ISSUE THREAD

**Issue by nameetpai-zz** [pchalamet/cassandra-sharp#50]
Others who do not have access to nuget.exe or the VS extension might find this url handy:
https://www.nuget.org/api/v2/package/{package-id}/{package-version}

I generally just download the cassandra-sharp-tools nupkg which contains all the binaries produced by this project.

E.g: https://www.nuget.org/api/v2/package/cassandra-sharp-tools/3.2.0

**Comment by pchalamet** [comment]
Will use msbuild/sdk project soon (see branch feature/msbuild-sdk for wip).
Everything will be merge in one big package because splitting interface and core is pretty much overkill.
