### ISSUE TITLE
get rid of InstallationDummyFile.txt

### ISSUE THREAD

**Issue by justmara** [pchalamet/cassandra-sharp#61]
If your project is connected to TFS, every time you run 'update-package' in nuget or just install cassandra-sharp from nuget, you get conflicts with 'InstallationDummyFile.txt does not exist', because package install script creates this file (i.e. it to source control) and then deletes. So you need to manually undo this file from every project in solution, every time you try to check-in after package install/update. That`s stupid. I don`t know what you use this file for, but I'm sure there is another, clearer way to achieve it, without hacky scripts with dummy files.

**Comment by pchalamet** [comment]
Will be fixed by creating a big package with all assemblies (ie: Core and Interfaces will be dropped).
See progress in branch feature/msbuild-sdk
