### ISSUE TITLE
Is there going to be an update to use the protocol v2?

### ISSUE THREAD

**Issue by ghostofcain** [pchalamet/cassandra-sharp#88]
Hi,

I was trying to do an insert with the "If Not Exists" flag (to prevent a race condition in one of my inserts) but received this exception:

Conditional updates are not supported by the protocol version in use. You need to upgrade to a driver using the native protocol v2.

I was wondering if there were any plans to upgrade the code to do this?

Many thanks in advance.

**Comment by pchalamet** [comment]
Hello,

I have no plan as of now. Unfortunately I have no time to enhance this project.

There are not that much options:
- use Datastax .net driver
- provide enhancement to cassandra-sharp to support v2 (PR welcome !). Should be easy.

- Pierre

**Comment by pchalamet** [comment]
V4 is available. Not released as nuget as of now.
