### ISSUE TITLE
cassandra socket exception

### ISSUE THREAD

**Issue by satishsoma** [pchalamet/cassandra-sharp#94]
{"Exception":"Caught and observed unobserved exception System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at Cassandra.HostConnectionPool.<>c__DisplayClass3.<CreateConnection>b__1(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0)

**Comment by pchalamet** [comment]
Hi,
Do you have the whole exception? 
This would be helpful to investigate.

**Comment by satishsoma** [comment]
{"Exception":"Caught and observed unobserved exception System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at Cassandra.HostConnectionPool.<>c__DisplayClass3.<CreateConnection>b__1(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at Cassandra.HostConnectionPool.<>c__DisplayClass3.<CreateConnection>b__1(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()<---\r\n","weid":"6039","frmt":"Error when event handler gets the unobserved task exception: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at Cassandra.HostConnectionPool.<>c__DisplayClass3.<CreateConnection>b__1(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()\r\n   --- End of inner exception stack trace ---\r\n---> (Inner Exception #0) System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond\r\n   at Cassandra.HostConnectionPool.<>c__DisplayClass3.<CreateConnection>b__1(Task`1 t)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.Execute()<---\r\n.
--

**Comment by pchalamet** [comment]
Sorry but you have to complain to Datastax instead I guess ;-)

I guess it's what you are looking for:
https://github.com/datastax/csharp-driver/blob/master/src/Cassandra/HostConnectionPool.cs

This repository is for CassandraSharp and is not linked to Datastax.

**Comment by satishsoma** [comment]
Thanks and I appreciate your help
